### ISSUE TITLE
cliphist requires popup even when cliphist-use-ivy is t

### ISSUE THREAD

**Issue by diamond-lizard** [redguardtoo/cliphist#12]
I don't want to use popup, so I have (setq cliphist-use-ivy t) but when I (require 'cliphist) I get an error:  *"Cannot open load file: Not a directory, popup"*.

It seems that cliphist is requiring popup unconditionally, even when cliphist-use-ivy is t.

**Comment by redguardtoo** [comment]
Yes, I will remove popup soon. Ivy is better choice

**Comment by peng051410** [comment]
It works for me! Thanks a lot.

**Comment by redguardtoo** [comment]
use ivy only
