### ISSUE TITLE
Read Flycut message no content

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/cliphist#15]
I use `cliphist-paste-item` show me Nothing in clipboard yet! But it already in it.
![image](https://user-images.githubusercontent.com/5512326/50438842-c6cb4f00-092a-11e9-97ae-114560243efb.png)

Can you help me?

**Comment by redguardtoo** [comment]
need more detail. flycut version? mac version?

**Comment by peng051410** [comment]
mac version: 10.14.2 (18C54)
flycut version: 1.5 (1.5)

**Comment by redguardtoo** [comment]
I also need the full content of `~/Library/Preferences/com.generalarcade.flycut.plist`.

**Comment by peng051410** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ShortcutRecorder mainHotkey</key>
	<dict>
		<key>keyCode</key>
		<integer>9</integer>
		<key>modifierFlags</key>
		<integer>786432</integer>
	</dict>
	<key>bezelAlpha</key>
	<real>0.25</real>
	<key>bezelHeight</key>
	<real>320</real>
	<key>bezelWidth</key>
	<real>500</real>
	<key>displayNum</key>
	<integer>10</integer>
	<key>loadOnStartup</key>
	<false/>
	<key>menuIcon</key>
	<integer>0</integer>
	<key>menuSelectionPastes</key>
	<true/>
	<key>popUpAnimation</key>
	<false/>
	<key>rememberNum</key>
	<integer>40</integer>
	<key>removeDuplicates</key>
	<false/>
	<key>savePreference</key>
	<integer>2</integer>
	<key>skipPasswordFields</key>
	<true/>
	<key>stickyBezel</key>
	<false/>
	<key>store</key>
	<dict>
		<key>displayLen</key>
		<integer>40</integer>
		<key>displayNum</key>
		<integer>10</integer>
		<key>jcList</key>
		<array>
			<dict>
				<key>Contents</key>
				<string>./GetWindowID Vivaldi ''</string>
				<key>Position</key>
				<integer>0</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>/usr/local/Cellar/getwindowid/1.0</string>
				<key>Position</key>
				<integer>1</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>./GetWindowID GLFW ''</string>
				<key>Position</key>
				<integer>2</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>brew install smokris/getwindowid/getwindowid</string>
				<key>Position</key>
				<integer>3</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>chunkc tiling::rule --owner "BetterTouchTool" --state float &amp;
</string>
				<key>Position</key>
				<integer>4</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>chunkc core::hotload 1
chunkc set window_use_cgs_move</string>
				<key>Position</key>
				<integer>5</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>1.5 (1.5)</string>
				<key>Position</key>
				<integer>6</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>看</string>
				<key>Position</key>
				<integer>7</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>
</string>
				<key>Position</key>
				<integer>8</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>081BCeQt0g4kXh1lPjOt0B9nQt0BCeQi</string>
				<key>Position</key>
				<integer>9</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx67f3f2afdcf601e2&amp;redirect_uri=http%3A%2F%2Fiyuedu.qq.com%2Fevent%2Faccount%2Fmyaccount.html&amp;response_type=code&amp;scope=snsapi_base&amp;state=formal002#wechat_redirect</string>
				<key>Position</key>
				<integer>10</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>bxLdikRXVbTPdHSM05e5u_TKPWO0u4GttU-yeQl3T3YTl-RI8cgT-0hqVx52Xn-NtVp_zBurkjUL3NpYrDqA6Q</string>
				<key>Position</key>
				<integer>11</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>17_Ot4LoUNj1jskFc4uw33pjzA-wB_I8CRm2RlEdgjhl9cHMCi9iBMIcYypnDk_RvLkj1TXb4ISqd09TrsJEpCmtVupqsgnsZewZ7Pfkvbqb5TV1Al3S01Gff9QLesWgDKOBOntCYCCiOzM5B9JWXHfACAFGQ</string>
				<key>Position</key>
				<integer>12</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>BookBase.QQReadingServiceNumberServer.QQReadingSNBindServantObj@</string>
				<key>Position</key>
				<integer>13</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>10.191.13.49</string>
				<key>Position</key>
				<integer>14</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>BookBase.QQReadingServiceNumberServer.QQReadingSNBindServantObj@</string>
				<key>Position</key>
				<integer>15</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>	10.242.18.210</string>
				<key>Position</key>
				<integer>16</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>refresh</string>
				<key>Position</key>
				<integer>17</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>QQReataidingServiceNumberServer</string>
				<key>Position</key>
				<integer>18</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>refresh</string>
				<key>Position</key>
				<integer>19</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>cliphist-linux</string>
				<key>Position</key>
				<integer>20</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>cliphist-paste-item</string>
				<key>Position</key>
				<integer>21</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>~/Library/Application Support/Flycut/com.generalarcade.flycut.plist</string>
				<key>Position</key>
				<integer>22</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>(add-hook 'message-send-hook 'my-message-pre-send-check-attachment)
</string>
				<key>Position</key>
				<integer>23</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
		</array>
		<key>rememberNum</key>
		<integer>40</integer>
		<key>version</key>
		<string>0.7</string>
	</dict>
	<key>wraparoundBezel</key>
	<false/>
</dict>
</plist>

**Comment by peng051410** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ShortcutRecorder mainHotkey</key>
	<dict>
		<key>keyCode</key>
		<integer>9</integer>
		<key>modifierFlags</key>
		<integer>786432</integer>
	</dict>
	<key>bezelAlpha</key>
	<real>0.25</real>
	<key>bezelHeight</key>
	<real>320</real>
	<key>bezelWidth</key>
	<real>500</real>
	<key>displayNum</key>
	<integer>10</integer>
	<key>loadOnStartup</key>
	<false/>
	<key>menuIcon</key>
	<integer>0</integer>
	<key>menuSelectionPastes</key>
	<true/>
	<key>popUpAnimation</key>
	<false/>
	<key>rememberNum</key>
	<integer>40</integer>
	<key>removeDuplicates</key>
	<false/>
	<key>savePreference</key>
	<integer>2</integer>
	<key>skipPasswordFields</key>
	<true/>
	<key>stickyBezel</key>
	<false/>
	<key>store</key>
	<dict>
		<key>displayLen</key>
		<integer>40</integer>
		<key>displayNum</key>
		<integer>10</integer>
		<key>jcList</key>
		<array>
			<dict>
				<key>Contents</key>
				<string>./GetWindowID Vivaldi ''</string>
				<key>Position</key>
				<integer>0</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>/usr/local/Cellar/getwindowid/1.0</string>
				<key>Position</key>
				<integer>1</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>./GetWindowID GLFW ''</string>
				<key>Position</key>
				<integer>2</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>brew install smokris/getwindowid/getwindowid</string>
				<key>Position</key>
				<integer>3</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>chunkc tiling::rule --owner "BetterTouchTool" --state float &amp;
</string>
				<key>Position</key>
				<integer>4</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>chunkc core::hotload 1
chunkc set window_use_cgs_move</string>
				<key>Position</key>
				<integer>5</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>1.5 (1.5)</string>
				<key>Position</key>
				<integer>6</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>看</string>
				<key>Position</key>
				<integer>7</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>
</string>
				<key>Position</key>
				<integer>8</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>081BCeQt0g4kXh1lPjOt0B9nQt0BCeQi</string>
				<key>Position</key>
				<integer>9</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx67f3f2afdcf601e2&amp;redirect_uri=http%3A%2F%2Fiyuedu.qq.com%2Fevent%2Faccount%2Fmyaccount.html&amp;response_type=code&amp;scope=snsapi_base&amp;state=formal002#wechat_redirect</string>
				<key>Position</key>
				<integer>10</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>bxLdikRXVbTPdHSM05e5u_TKPWO0u4GttU-yeQl3T3YTl-RI8cgT-0hqVx52Xn-NtVp_zBurkjUL3NpYrDqA6Q</string>
				<key>Position</key>
				<integer>11</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>17_Ot4LoUNj1jskFc4uw33pjzA-wB_I8CRm2RlEdgjhl9cHMCi9iBMIcYypnDk_RvLkj1TXb4ISqd09TrsJEpCmtVupqsgnsZewZ7Pfkvbqb5TV1Al3S01Gff9QLesWgDKOBOntCYCCiOzM5B9JWXHfACAFGQ</string>
				<key>Position</key>
				<integer>12</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>BookBase.QQReadingServiceNumberServer.QQReadingSNBindServantObj@</string>
				<key>Position</key>
				<integer>13</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>10.191.13.49</string>
				<key>Position</key>
				<integer>14</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>BookBase.QQReadingServiceNumberServer.QQReadingSNBindServantObj@</string>
				<key>Position</key>
				<integer>15</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>	10.242.18.210</string>
				<key>Position</key>
				<integer>16</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>refresh</string>
				<key>Position</key>
				<integer>17</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>QQReataidingServiceNumberServer</string>
				<key>Position</key>
				<integer>18</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>refresh</string>
				<key>Position</key>
				<integer>19</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>cliphist-linux</string>
				<key>Position</key>
				<integer>20</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>cliphist-paste-item</string>
				<key>Position</key>
				<integer>21</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>~/Library/Application Support/Flycut/com.generalarcade.flycut.plist</string>
				<key>Position</key>
				<integer>22</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>(add-hook 'message-send-hook 'my-message-pre-send-check-attachment)
</string>
				<key>Position</key>
				<integer>23</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
		</array>
		<key>rememberNum</key>
		<integer>40</integer>
		<key>version</key>
		<string>0.7</string>
	</dict>
	<key>wraparoundBezel</key>
	<false/>
</dict>
</plist>
`

**Comment by peng051410** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ShortcutRecorder mainHotkey</key>
	<dict>
		<key>keyCode</key>
		<integer>9</integer>
		<key>modifierFlags</key>
		<integer>786432</integer>
	</dict>
	<key>bezelAlpha</key>
	<real>0.25</real>
	<key>bezelHeight</key>
	<real>320</real>
	<key>bezelWidth</key>
	<real>500</real>
	<key>displayNum</key>
	<integer>10</integer>
	<key>loadOnStartup</key>
	<false/>
	<key>menuIcon</key>
	<integer>0</integer>
	<key>menuSelectionPastes</key>
	<true/>
	<key>popUpAnimation</key>
	<false/>
	<key>rememberNum</key>
	<integer>40</integer>
	<key>removeDuplicates</key>
	<false/>
	<key>savePreference</key>
	<integer>2</integer>
	<key>skipPasswordFields</key>
	<true/>
	<key>stickyBezel</key>
	<false/>
	<key>store</key>
	<dict>
		<key>displayLen</key>
		<integer>40</integer>
		<key>displayNum</key>
		<integer>10</integer>
		<key>jcList</key>
		<array>
			<dict>
				<key>Contents</key>
				<string>./GetWindowID Vivaldi ''</string>
				<key>Position</key>
				<integer>0</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>/usr/local/Cellar/getwindowid/1.0</string>
				<key>Position</key>
				<integer>1</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>./GetWindowID GLFW ''</string>
				<key>Position</key>
				<integer>2</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>brew install smokris/getwindowid/getwindowid</string>
				<key>Position</key>
				<integer>3</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>chunkc tiling::rule --owner "BetterTouchTool" --state float &amp;
</string>
				<key>Position</key>
				<integer>4</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>chunkc core::hotload 1
chunkc set window_use_cgs_move</string>
				<key>Position</key>
				<integer>5</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>1.5 (1.5)</string>
				<key>Position</key>
				<integer>6</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>看</string>
				<key>Position</key>
				<integer>7</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>
</string>
				<key>Position</key>
				<integer>8</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>081BCeQt0g4kXh1lPjOt0B9nQt0BCeQi</string>
				<key>Position</key>
				<integer>9</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx67f3f2afdcf601e2&amp;redirect_uri=http%3A%2F%2Fiyuedu.qq.com%2Fevent%2Faccount%2Fmyaccount.html&amp;response_type=code&amp;scope=snsapi_base&amp;state=formal002#wechat_redirect</string>
				<key>Position</key>
				<integer>10</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>bxLdikRXVbTPdHSM05e5u_TKPWO0u4GttU-yeQl3T3YTl-RI8cgT-0hqVx52Xn-NtVp_zBurkjUL3NpYrDqA6Q</string>
				<key>Position</key>
				<integer>11</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>17_Ot4LoUNj1jskFc4uw33pjzA-wB_I8CRm2RlEdgjhl9cHMCi9iBMIcYypnDk_RvLkj1TXb4ISqd09TrsJEpCmtVupqsgnsZewZ7Pfkvbqb5TV1Al3S01Gff9QLesWgDKOBOntCYCCiOzM5B9JWXHfACAFGQ</string>
				<key>Position</key>
				<integer>12</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>BookBase.QQReadingServiceNumberServer.QQReadingSNBindServantObj@</string>
				<key>Position</key>
				<integer>13</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>10.191.13.49</string>
				<key>Position</key>
				<integer>14</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>BookBase.QQReadingServiceNumberServer.QQReadingSNBindServantObj@</string>
				<key>Position</key>
				<integer>15</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>	10.242.18.210</string>
				<key>Position</key>
				<integer>16</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>refresh</string>
				<key>Position</key>
				<integer>17</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>QQReataidingServiceNumberServer</string>
				<key>Position</key>
				<integer>18</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>refresh</string>
				<key>Position</key>
				<integer>19</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>cliphist-linux</string>
				<key>Position</key>
				<integer>20</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>cliphist-paste-item</string>
				<key>Position</key>
				<integer>21</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>~/Library/Application Support/Flycut/com.generalarcade.flycut.plist</string>
				<key>Position</key>
				<integer>22</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
			<dict>
				<key>Contents</key>
				<string>(add-hook 'message-send-hook 'my-message-pre-send-check-attachment)
</string>
				<key>Position</key>
				<integer>23</integer>
				<key>Type</key>
				<string>NSStringPboardType</string>
			</dict>
		</array>
		<key>rememberNum</key>
		<integer>40</integer>
		<key>version</key>
		<string>0.7</string>
	</dict>
	<key>wraparoundBezel</key>
	<false/>
</dict>
</plist>
`

**Comment by peng051410** [comment]
[com.generalarcade.flycut.txt](https://github.com/redguardtoo/cliphist/files/2714763/com.generalarcade.flycut.txt)

I modified the suffix name of the file.

**Comment by redguardtoo** [comment]
232ab0b support flycut 1.6 which might use binary plist (Chen Bin)

**Comment by peng051410** [comment]
Thank you fix it. but not i found when i run "cliphist-read-items" command, i got message "Cannot open load file: No such file or directory, cliphist". What is the reason?

**Comment by redguardtoo** [comment]
It works on my computer, tested with flycut 1.8. After installed latest cliphist, follow readme.

**Comment by peng051410** [comment]
Still not working. flycut version 1.8.2. How to debug it?

**Comment by redguardtoo** [comment]
`M-x eval-expression (cliphist-flycut-guess-preference-path)`, should output the flycut config file path. Could you double check that file exist? Then send me the content of that file.
Besides, check your flycut setup, make sure flycut save the content after each copying.

**Comment by peng051410** [comment]
This is the output:
`Debugger entered--Lisp error: (void-function cliphist-flycut-guess-preference-path)
  (cliphist-flycut-guess-preference-path)
  eval((cliphist-flycut-guess-preference-path) nil)
  eval-expression((cliphist-flycut-guess-preference-path) nil nil 127)
  funcall-interactively(eval-expression (cliphist-flycut-guess-preference-path) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
`
The command not found?

**Comment by redguardtoo** [comment]
You need open `~/.emacs.d/elpa/cliphist-0.5.5/cliphist-flycut.el` and `M-x eval-buffer` first.

**Comment by peng051410** [comment]
The command `(cliphist-flycut-guess-preference-path)` result is:
"/Users/tomyli/Library/Preferences/com.generalarcade.flycut.plist", it's a binary file.
What's next?

**Comment by peng051410** [comment]
Binary file
[com.generalarcade.flycut.plist.txt](https://github.com/redguardtoo/cliphist/files/2758076/com.generalarcade.flycut.plist.txt)
I add the .txt suffix

**Comment by redguardtoo** [comment]
Thanks. So the file path is correct. It's possible the file content is different. I need some time to investigate

**Comment by redguardtoo** [comment]
The file is fine.

**Comment by peng051410** [comment]
It works for me! Thanks a lot.
