### ISSUE TITLE
ability to clear the emacs kill-ring

### ISSUE THREAD

**Issue by boudiccas** [redguardtoo/cliphist#2]
I'm using 'cliphist' and its very good, and I can clear the parcellite history, but am unable to clear the kill-ring. Can there be a function in 'cliphist' that when called will do this please?

**Comment by redguardtoo** [comment]
http://superuser.com/questions/546619/clear-the-kill-ring-in-emacs

**Comment by boudiccas** [comment]
Thanks, I am aware of that page, and have used its information as my jumping-off point into getting a working `clear kill-ring` . I'm now involved in a discussion on the `help-gnu-emacs` mailing list with regard to getting a working script. When I actually do have such a script I'll post it here so that you can include it in `cliphist` if you want to.

**Comment by boudiccas** [comment]
Sorry, closed in error.

**Comment by boudiccas** [comment]
```
(defun clear-kill-ring ()
  "Clear the kill ring variable"
  (interactive)
  (setq kill-ring nil
        kill-ring-yank-pointer nil))
(global-set-key (kbd "s-/") 'clear-kill-ring)
```
