### ISSUE TITLE
Use ivy-mode or helm-mode to select the entry?

### ISSUE THREAD

**Issue by xuhdev** [redguardtoo/cliphist#4]
I think `cliphist` can probably share some of the similar interfaces with `counsel-yank-pop` and `helm-yank-pop`, which are very useful...

**Comment by redguardtoo** [comment]
thanks, I added ivy-mode support.
8ff43ae can use ivy-mode UI (Chen Bin)

**Comment by xuhdev** [comment]
It works now. Thanks!
