### ISSUE TITLE
Add option to select clipit or parcellite

### ISSUE THREAD

**Issue by arkhan** [redguardtoo/cliphist#7]

**Comment by redguardtoo** [comment]
Insert below code into `~/.emacs`, then `M-x cliphist-select-item` (https://github.com/rolandwalker/simpleclip required),
```lisp
(defun my-select-cliphist-item (num str)
  (unless (featurep 'simpleclip)
    (require 'simpleclip))
  (simpleclip-set-contents str))
(setq cliphist-select-item-callback 'my-select-cliphist-item)
```

**Comment by arkhan** [comment]
but dont read clipit history 

https://github.com/CristianHenzel/ClipIt

**Comment by redguardtoo** [comment]
my computer crashed, need one week to restore, so be patient.

**Comment by redguardtoo** [comment]
689051b support ClipIt at Linux (Chen Bin)
