### ISSUE TITLE
Doesn't work with FlyCut v1.8.2 (1.fe5bb21.10.1612

### ISSUE THREAD

**Issue by wallacewinfrey** [redguardtoo/cliphist#9]
Not sure if the data file location referred to in cliphist-flycut.el, "~/Library/Application Support/Flycut/com.generalarcade.flycut.plist", is still accurate with this version.

With the version of Flycut I'm running (built from Github via Homebrew) the relevant file appears to be ~/Library/Preferences/com.generalarcade.flycut.plist; however even though I can see clipboard history in this file, modifying cliphist-flycut.el to point to this file results in a parsing error.

**Comment by redguardtoo** [comment]
Thanks. Could you paste the full content of the file here?

**Comment by redguardtoo** [comment]
try new version.
acbd978 more flexilble to read flycut preference file (Chen Bin)
